apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: eazybank
  labels:
    app: kafka
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: eazybank
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
        app.kubernetes.io/name: kafka
        app.kubernetes.io/part-of: eazybank
    spec:
      containers:
        - name: kafka
          image: apache/kafka:4.3.1
          ports:
            - name: broker
              containerPort: 9092
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@localhost:9093"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: CLUSTER_ID
              value: "MkU3OEVBNTcwNTJENDM2Qk"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
          startupProbe:
            tcpSocket:
              port: 9092
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 9092
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9092
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: eazybank
  labels:
    app: kafka
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: eazybank
spec:
  selector:
    app: kafka
  type: ClusterIP
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
