spring:
  application:
    name: "configserver"
  profiles:
#     active: native
    active: git
  cloud:
    config:
      server:
#         native:
#           search-locations: "classpath:/config"
#           search-locations: "file:///Users/berrahmaach//IdeaProjects//microservices//config"
        git:
          uri: "https://github.com/achour94/eazybytes-config.git"
          default-label: main # branch name
          timeout: 5 # represent the time in seconds to wait for the git clone
          clone-on-start: true # clone the repository on startup
          force-pull: true # force pull the repository on startup
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071
