apiVersion: v2
name: gatewayserver
description: Spring Cloud Gateway
type: application
version: 0.1.0
appVersion: "s17"

dependencies:
  - name: eazybank-common
    version: 0.1.0
    repository: "file://../../eazybank-common"
