apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
  namespace: eazybank
  labels:
    app: accounts
    app.kubernetes.io/name: accounts
    app.kubernetes.io/part-of: eazybank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
        app.kubernetes.io/name: accounts
        app.kubernetes.io/part-of: eazybank
    spec:
      containers:
      - name: accounts
        image: eazybytes/accounts:s14
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_CONFIG_IMPORT
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: KAFKA_BROKER
        - name: MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: OTLP_TRACES_ENDPOINT
        - name: MANAGEMENT_OPENTELEMETRY_LOGGING_EXPORT_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: OTLP_LOGS_ENDPOINT
        - name: MANAGEMENT_OTLP_METRICS_EXPORT_URL
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: OTLP_METRICS_ENDPOINT
        resources:
          requests:
            cpu: 250m
            memory: 384Mi
          limits:
            cpu: 500m
            memory: 700Mi
        startupProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          failureThreshold: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
  namespace: eazybank
  labels:
    app: accounts
    app.kubernetes.io/name: accounts
    app.kubernetes.io/part-of: eazybank
spec:
  selector:
    app: accounts
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
